### ISSUE TITLE
Κώδικας για εμφάνιση διαδρομής μεταξύ τοποθεσίας - Supermarket

### ISSUE THREAD

**Issue by makisp** [teicm-project/supermarket-finder#12]
- Θα εμφανίζει την διαδρομή μεταξύ της τοποθεσίας του χρήστη με την τοποθεσία του κοντινότερου Supermarket

**Comment by Miracle1995** [comment]
Θα το ψαξω εγω εαν θελει κανεις να το δουμε μαζι κομπλε αλλιως θα το κοιταξω εγω αυτες τις μερες

**Comment by makisp** [comment]
Ναι ρε κοίταξε το και αν κάνεις κάτι ανέβασε το

**Comment by Miracle1995** [comment]
Οκ κομπλε θα το τσεκαρω αν ειναι
