### ISSUE TITLE
Κώδικας για υπολογισμό κοντινότερου Supermarket

### ISSUE THREAD

**Issue by makisp** [teicm-project/supermarket-finder#9]
Ο κώδικας θα ελέγχει τις καταχωρήσεις της βάσης (συντεταγμένες x, y) και θα βρίσκει ύστερα από υπολογισμούς το κοντινότερο Supermarket από την θέση του χρήστη.
- Θα βάζει το κοντινότερο Supermarket σε global μεταβλητή
- Θα τοποθετεί marker για κάθε Supermarket στον χάρτη
- Θα καλείται μέσα από το MapsActivity

**Comment by EvanPetr** [comment]
Παιδία να το αναλάβω εγώ αυτό?

**Comment by makisp** [comment]
Ήθελε και ο Τσέλιος, αν μπορείτε να το χωρίσετε κάπως...
